### ISSUE TITLE
Using innerJoinWith() on tables with Translate behavior fails

### ISSUE THREAD

**Issue by berarma** [AD7six/cakephp-shadow-translate#52] opened 2018-08-06 10:57 UTC
The translated fields are replaced in the query but the translation tables aren't joined in.

UPDATE:

src/Model/Table/CountriesTable.php:
```
<?php
namespace App\Model\Table;

use Cake\ORM\Table;

class CountriesTable extends Table
{

    public function initialize(array $config)
    {
        $this->addBehavior('ShadowTranslate.ShadowTranslate', [
            'translationTable' => 'CountriesI18n',
            'defaultLocale' => 'es_ES',
            'allowEmptyTranslations' => false,
        ]);

        $this->hasMany('Destinations');
    }
}
```

src/Model/Table/DestinationsTable.php:
```
<?php
namespace App\Model\Table;

use Cake\ORM\Table;

class DestinationsTable extends Table
{
    public function initialize(array $config)
    {
        $this->addBehavior('ShadowTranslate.ShadowTranslate', [
            'translationTable' => 'DestinationsI18n',
            'defaultLocale' => 'es_ES',
            'allowEmptyTranslations' => false,
        ]);
}

```

```
\Cake\I18n\I18n::setLocale('en_GB');
$Destinations = \Cake\ORM\TableRegistry::get('Destinations');
$d = $Destinations
  ->find()
  ->innerJoinWith('Countries', function ($q) {
    return $q->where(['slug' => 'spain']);
  })
  ->where([$Destinations->translationField('url_friendly') => 'valencia'])
  ->first();
```

Result: PDOException with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'CountriesTranslation.slug' in 'on clause''

Generated query:

SELECT Destinations.id AS `Destinations__id`, Destinations.created AS `Destinations__created`, Destinations.name AS `Destinations__name`, Destinations.url_friendly AS `Destinations__url_friendly`, Destinations.description AS `Destinations__description`, Destinations.guide AS `Destinations__guide`, DestinationsTranslation.id AS `DestinationsTranslation__id`, DestinationsTranslation.locale AS `DestinationsTranslation__locale`, DestinationsTranslation.name AS `DestinationsTranslation__name`, DestinationsTranslation.url_friendly AS `DestinationsTranslation__url_friendly`, DestinationsTranslation.description AS `DestinationsTranslation__description`, DestinationsTranslation.guide AS `DestinationsTranslation__guide` FROM destinations Destinations INNER JOIN countries Countries ON (CountriesTranslation.slug = :c0 AND Countries.id =  (Destinations.country_id)) LEFT JOIN destinations_i18n DestinationsTranslation ON (DestinationsTranslation.locale = :c1 AND Destinations.id = (DestinationsTranslation.id)) WHERE DestinationsTranslation.url_friendly = :c2

**Comment by ADmad** [comment] 2018-08-06 11:47
Please provide actual code to reproduce your issue and generated query.

**Comment by berarma** [comment] 2018-08-06 12:27
I've added real code to the first post. Thanks.

**Comment by ADmad** [comment] 2018-08-06 12:30
What's your current locale? If current local is same as default locale `es_ES` there won't be any joins done with the translation tables.

**Comment by ADmad** [comment] 2018-08-06 12:34
Ah, the issue is caused by `return $q->where(['slug' => 'spain']);`. It ends up generating `CountriesTranslation.slug = :c0 ` instead of `Countries.slug = :c0 ` in the join conditions in query.

**Comment by ADmad** [comment] 2018-08-06 12:41
Does using `return $q->where(['Countries.slug' => 'spain']);` fix the issue?

**Comment by berarma** [comment] 2018-08-06 12:42
> Does using return $q->where(['Countries.slug' => 'spain']); fix the issue?

It doesn't fail but it's not using the translated slug so the result is wrong.

**Comment by berarma** [comment] 2018-08-07 10:15
I'm trying to fix the issue. This is from the same query object:

```
'contain' => [
		'DestinationsTranslation' => [],
		'Countries' => [
			'CountriesTranslation' => []
		]
	],
'matching' => [
		'Countries' => [
			'queryBuilder' => object(Closure) {
				
			},
			'matching' => true,
			'joinType' => 'INNER',
			'fields' => false
		]
	],
```

CountriesTranslation is in the contain array but not in the matching array. CakePHP ignores the table in the contain array when the same table is in the matching array. How could this be fixed?

**Comment by ADmad** [comment] 2018-08-07 11:53
This sounds like an issue with the ORM rather than the plugin. Matching is a PITA.

/cc @lorenzo

**Comment by lorenzo** [comment] 2018-08-07 14:01
I have very little knowledge about how this plugin is working. Can you try to reduce the problem to a single test and I can look at it? Better open a ticket in cakephp/cakephp

**Comment by berarma** [comment] 2018-08-07 15:19
I've created issue [cakephp/cakephp/issues/12440](url).

Thanks for the help!

**Comment by ADmad** [comment] 2018-08-07 16:00
@berarma I think for now using `contain()` instead of `innerJoinWith()` should give you the desired result (albeit with countries field which you probably don't need).

**Comment by berarma** [comment] 2018-08-08 10:59
Thanks @ADmad. I'll be using this solution for now.

**Comment by ADmad** [comment] 2018-08-10 17:43
Closing as this is an issue in the ORM and not the plugin.

**Closed by ADmad** 2018-08-10 17:43 UTC
Labels: bug
